# Generated by Django 4.1.7 on 2023-02-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="short_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
