# Generated by Django 4.1.7 on 2023-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_alter_company_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="value",
            field=models.CharField(default="", max_length=300),
            preserve_default=False,
        ),
    ]
