# Generated by Django 4.1.7 on 2023-02-20 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_address_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="companytrade",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="coveredpostcode",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="covered_postcodes",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="taxinfo",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_infos",
                to="companies.company",
            ),
        ),
    ]
