# Generated by Django 4.1.7 on 2023-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_alter_address_company_alter_bankaccount_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companytrade",
            name="note",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
    ]
