# Generated by Django 4.1.7 on 2023-02-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_alter_companytrade_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="type",
            field=models.CharField(
                choices=[("office", "Office"), ("billing", "billing")],
                default="office",
                max_length=7,
            ),
        ),
    ]
