# Generated by Django 4.1.7 on 2023-02-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_address_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="type",
            field=models.CharField(
                choices=[("personal", "Personal"), ("business", "Business")],
                default="business",
                max_length=8,
            ),
            preserve_default=False,
        ),
    ]
