# Generated by Django 4.1.7 on 2023-02-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_bankaccount_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="history",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Information about the history of the company",
                max_length=500,
            ),
        ),
    ]
